services:
  # Backend Node.js Service
  - type: web
    name: zoom-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://vasutrehan69_db_user:radha%40madhav6@cluster1.l6osvxu.mongodb.net/"
        # You will need to replace this with your actual MongoDB URI in the Render dashboard.
      - key: PORT
        value: 8000
